### ISSUE TITLE
I have 99 issues and a @pewcodes ain't one

### ISSUE THREAD

**Issue by linxea** [linxea/senstivedatafigure#2]

**Comment by pewcodes** [comment]
One of the main issue here is: 'i' am excluded in this **senstivedatafigure** repo 😭 and that's who to git.**Blame**??

**Comment by linxea** [comment]
Git out of here! That's gitmpossible! I've added you as a contributor with full access to the repo. You should be able to git push all your blames to the repo without any problem.

**Comment by pewcodes** [comment]
me git it.

**Comment by linxea** [comment]
git job
